export default {
  DB_CREDENTIALS_NAME: process.env.DB_CREDENTIALS_NAME,
  DB_SETTINGS_NAME: process.env.DB_SETTINGS_NAME,
  STAGE: process.env.STAGE,
  NODE_ENV: process.env.NODE_ENV,
  ASSETS_BUCKET_NAME: process.env.ASSETS_BUCKET_NAME,
  JWT_SECRET_KEY: process.env.JWT_SECRET_KEY,
  JWT_REFRESH_SECRET_KEY: process.env.JWT_REFRESH_SECRET_KEY,
  REGION: process.env.REGION,
  EMAIL_FROM_ADDRESS: process.env.EMAIL_FROM_ADDRESS,
};
